displaymanagers: [ sddm ]
basicSetup: false
sysconfigSetup: false
defaultDesktopEnvironment:
  executable: /usr/bin/startplasma-wayland
  desktopFile: plasma
sddm:
  configuration_file: /etc/sddm.conf
