showSupportUrl: true
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false
requirements:
  requiredStorage: 21
  requiredRam: 2
  internetCheckUrl: https://geo.mirror.pkgbuild.com/core/os/x86_64/core.db
  check: [ storage, ram, power, internet, root ]
  required: [ storage, ram, internet, root ]
geoip:
  style: none
  url: ""
  selector: ""
